### ISSUE TITLE
Closes windows on multiplayer

### ISSUE THREAD

**Issue by ghost** [l0k1/A-10#22]
I'm using this aircraft on multiplayer and when I open a window from "multiplayer" section on top it closes automatically. For example "pilot list" window closes. Also on map I can't select "traffic" section "on" because it turns off it too.

**Comment by ZorkaA** [comment]
Damage is on by-default (which includes the anti-cheat measures you are talking about). If you turn it off (A-10 > Toggle Damage) it'll allow you to access all of those options.
