### ISSUE TITLE
Add topics to this repo

### ISSUE THREAD

**Issue by ghost** [l0k1/A-10#23]
Add topics to this repo for make it more visible like this:
https://github.com/NikolaiVChr/f16
https://github.com/Octal450/MD-11

**Comment by SammySkycrafts** [comment]
From what i can see this would be down to @l0k1 as Repo owner. I do not seem to have access to the area where you assign these.

**Comment by ZorkaA** [comment]
At least something along the lines of "Flightgear," "Simulation," "A-10"

**Comment by l0k1** [comment]
added topcis.
