### ISSUE TITLE
RWR: self launched weapons occasionally cause priority unknown threat to appear

### ISSUE THREAD

**Issue by SammySkycrafts** [l0k1/A-10#24]
![image](https://user-images.githubusercontent.com/77464976/178079735-30089c62-e7f2-474a-a5fa-5abecbf2e974.png)

**Comment by ZorkaA** [comment]
Just tested, this also applies to LAU-68s and Mk-82s (except for the priority designation).

![After a salvo of Hydras](https://user-images.githubusercontent.com/68531996/184477584-211e4178-e149-4cc4-8f0b-d32ee787d253.png)

**Comment by SammySkycrafts** [comment]
Closing - Unable to reliably reproduce.

**Comment by SammySkycrafts** [comment]
Reopening as still present.

**Comment by SammySkycrafts** [comment]
Hopefully fixed with [19e6007](https://github.com/l0k1/A-10/commit/19e60077aaa09b989177ad66495eefb523f993d9) - Need to test
