### ISSUE TITLE
LAU-68s not displaying the correct number of available rockets on Armament panel

### ISSUE THREAD

**Issue by ZorkaA** [l0k1/A-10#25]
Station markers for empty launchers do not display the error light (Orange), and continue to be shown as active/available (Green). Other stores work fine.

**Comment by SammySkycrafts** [comment]
Closing issue - Behaviour matches what is shown in the -1-1
<img width="620" alt="image" src="https://user-images.githubusercontent.com/77464976/185214532-ccc841c3-a94a-422a-ab7d-66ffe8aeec4f.png">
