### ISSUE TITLE
Key to reset cockpit view to default position

### ISSUE THREAD

**Issue by ghost** [l0k1/A-10#37]
At other aircraft of FlightGear, usually key "c" stands for resetting the view but at this aircraft there isn't any button assigned for this from what I saw.

**Comment by ZorkaA** [comment]
We will look into exploring whether it would be beneficial to add this as a feature in such a way as not to interfere with existing systems.

**Comment by SammySkycrafts** [comment]
@gretchenlyon This has now been added in. The key is `Q`, Shift + Q. This was chosen to stay in alignment with other military aircraft in FlightGear that have this binding.

Thanks for the reminder
